### PR TITLE
Added pnpm-lock.yaml and enforce pnpm use

### LINKED ISSUE #2: Enforcing a package manager and committing a lockfile
We should commit the lockfile to our repo, regardless of the package manager we choose. Longer read [here](https://www.arahansen.com/the-ultimate-guide-to-yarn-lock-lockfiles/#:~:text=Every%20project%20using%20yarn%20should,for%20installing%20the%20wrong%20packages.). The part that matters:

> **Should you commit yarn.lock?**
> Every project using yarn should commit the yarn lockfile to source control. The lockfile is the source of truth for telling other developers how to install dependencies for your project.
> 
> Without this lockfile, other developers will be at risk for installing the wrong packages. This could lead to any number of incompatibilities where there is a version mismatch and the project won't build or run. You don't want to be stuck saying "works on my machine!".

As far as package manager, I will advocate for using `pnpm` because, in my experience, it's fastest. But Yarn and NPM are great too if there's strong preference there.

@daltn @dereksaffe How yall feelin

### PR DESCRIPTION
**Pull request by madisonbullard**
Related issue: https://github.com/daltn/rave-cafe-blog/issues/2

### CODE REVIEW

**Review by daltn — DISMISSED** [review]
looks good and vercel supports pnpm so let's go for it.

**Comment by daltn** [comment]
the error above will be fixed when i update the vercel config

**Comment by daltn** [comment]
for the build command would it make a difference to go from `npm run build` to `pnpm run build` ?

**Comment by daltn** [comment]
> for the build command would it make a difference to go from `npm run build` to `pnpm run build` ?

hmmmm so i updated the vercel build command to use `pnpm run build` and it does not seem to want to build on vercel. any ideas what it could be?

**Comment by daltn** [comment]
Vercel build:
```
Build Failed

Command "pnpm run build" exited with 1
```

**Comment by madisonbullard** [comment]
I'll take a look soon. If I hit any friction I'll probably scrap this plan and just use NPM lol. Thanks for helping @daltn

**Comment by madisonbullard** [comment]
We're limited to 1 user in Vercel so going back and forth between the code and the logs is more hassle than its worth right now. Lets just use NPM since it works.

**Pull request closed without merging**
